services:
  - type: web
    name: telegram-signal-forwarder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SOURCE_CHANNEL_USERNAME
        sync: false
      - key: TARGET_CHANNEL_USERNAME
        sync: false
